language: csharp
solution: windowsdriver.sln

deploy:
  provider: releases
  api_key: "b763e2c61af285d06bd997209a117a00175ca57d"
  file:
    - "DotAmf.dll"
    - "DotAmf.pdb"
    - "FlaUI.Core.dll"
    - "FlaUI.Core.xml"
    - "FlaUI.UIA3.dll"
    - "FlaUI.UIA3.xml"
    - "Interop.UIAutomationClient.dll"
    - "windowsdriver.exe"
    - "windowsdriver.exe.config"
    - "windowsdriver.pdb"
  skip_cleanup: true
  on:
    tags: true
    
notifications:
  slack: agilitest:89arTDhysVkKJ7TGJ2qw6Xwv