language: csharp
solution: windowsdriver.sln
branches:
  only:
    - master
before_deploy:
  - cd /home/travis/build/pierrehub2b/windowsdriver/bin/Release
  - zip windowsdriver.zip windowsdriver.exe DotAmf.dll FlaUI.Core.dll FlaUI.UIA3.dll Interop.UIAutomationClient.dll
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: /home/travis/build/pierrehub2b/windowsdriver/bin/Release
  keep_history: true
  on:
    branch: master
  skip_cleanup: true
notifications:
  slack: agilitest:89arTDhysVkKJ7TGJ2qw6Xwv
